language: perl
sudo: false
matrix:
  include:
  - perl: "5.8"
    dist: trusty
  - perl: "5.10"
    dist: trusty
  - perl: "5.12"
    dist: trusty
  - perl: "5.26"
  - perl: "5.30"
install:
  - cpanm -nq --with-configure --installdeps .
